<h3>User authorization</h3>
<p><?php _e('Allow'); ?> <strong><?php echo $client['name'];?></strong> <?php _e('to access the following data'); ?>:</p>
<ul>
    <li>
<!--        <input type="checkbox" name="base" chekced="disable" >-->
<?php
    if ($client['scope'] == 'base') {
        echo 'User Infomation';
    }
?>
    </li>
</ul>
<form method="post">

<input type="hidden" value=1 name="auth">
<input type="submit" value="<?php _e('Authorize'); ?>">
<button onclick="back()">cancel</button>
</form>
<script type="text/javascript">
function back()
{
    window.location.href = "http://<?php echo $backuri . '?cancle=1' ?>";
}
</script>