<style type="text/css">
.client-list-container{
	padding-left: 50px;
	
	width: 600px;
}
.client-item{
	list-style: none;
	padding-top: 20px;
}
.client-logo{
position: relative;
float: left;
width: 75px;
}
.client-logo a{
height: 75px;
width: 75px;
display: block;
position: absolute;
top: 0;
left: -3px;
z-index: 20;
}
.client-logo img{
	position: absolute;
height: 64px;
width: 64px;
z-index: 0;
}
.client-content{
	margin-left: 100px;
}
.client-info{
float: left;
width: 400px;
padding-top: 2px;
}
.client-handler{
	float: right;
	padding-top: 20px;
}
</style>



<div class="client-list-container">
	<ul class="client-list">
		<?php foreach ($client as $value) {d($value);?> 
		<li class="client-item">
			<div class="client-logo">
				<a class="pic" href="list?id=<?php echo $value['id'];?>"></a>
				<img class="img" src="<?php echo $value['logo'];?>">
			</div>
			<div class="client-content clearfix">
				<div class="client-info">
					<p class="client-name">
						<a href="list?id=<?php echo $value['id'];?>"><?php echo $value['name'];?></a>
					</p>
					<p class="client-desc">
						<?php echo $value['description'];?>
					</p>
				</div>
				<div class="client-handler">
					<?php echo $value['isverify'] ? _t('verified') : _t('Not verified');?>
				</div>
			</div>

		</li>
 		<?php } ?>
	</ul>	
</div>
