<style type="text/css">
.client-reg-form{
	padding-top: 50px;
}
.client-reg-form div label{
width: 200px;
float: left;
text-align: right;
padding-right: 20px;
}
.client-reg-head {
	padding-top: 15px;
	padding-left: 160px;
	font-size: 22px;
}
</style>
<div class="client-reg">
<div class="client-reg-head">Client register</div>
<div class="client-reg-form">
<?php echo $this->form()->openTag($form); ?>

<div>
	<?php $element = $form->get('name'); ?>
	<?php echo $this->formLabel($element) ?>
	<?php echo $this->formElement($element) ?> 
</div>

<div>
	<?php $element = $form->get('address'); ?>
	<?php echo $this->formLabel($element) ?>
	<?php echo $this->formElement($element) ?> 
</div>

<div>
	<?php $element = $form->get('redirect_uri'); ?>
	<?php echo $this->formLabel($element) ?>
	<?php echo $this->formElement($element) ?>
</div>

<div>
	<?php $element = $form->get('description'); ?>
	<?php echo $this->formLabel($element) ?>
	<?php echo $this->formElement($element) ?>
</div>

<div>
	<?php $element = $form->get('logo'); ?>
	<?php echo $this->formLabel($element) ?>
	<?php echo $this->formElement($element) ?> 
</div>

<div>
	<label></label>
	<?php $element = $form->get('submit'); ?>
	<?php echo $this->formElement($element) ?>
</div>

<?php echo $this->form()->closeTag();?>
</div>
</div>