<h2 class="page-header"><?php _e('Client List'); ?></h2>
<a style="float:right;" class="btn btn-primary" href="scope"><?php _e('Go To Apply Scope');?></a>
<table class="table">
    <tr>
        <td><?php _e('logo')?></td>
        <td><?php _e('name')?></td>
        <td><?php _e('operation')?></td>
    </tr>
    <?php foreach ($client as $value) {?>
    <tr>
        <td>
            <a class="pic" href="list?id=<?php echo $value['id'];?>">
                <img class="img" src="<?php echo $value['logo'];?>">
            </a>
        </td>
        <td>
            <a href="list?id=<?php echo $value['id'];?>"><?php echo $value['name'];?></a>
        </td>   
        <td>
        <?php 
            if ($value['verify'] == 0) { 
            echo '<button id="' . $value['id'] . '" class="verify-btn">' . __('verify client') . '</button>';
            } elseif ($value['verify'] == 1) {
                _e('verifing');
            } else {
                echo '<p>' . __('Have Been Verified') . '</p>';
            }
        ?>
        </td>
    </tr>
    <?php }?>
</table>


<script type="text/javascript">
    $(".verify-btn").click(function(){
        $.ajax({
            type : "get",
            url : "verify",
            data : {id : this.id},
            success: function(data) {
                window.location.reload();
            }
        });
    }); 
</script>
