<ul class="nav nav-tabs">
    <li class="active">
        <a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php _e('Client List'); ?>">
            <?php _e('Client List'); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url('', array('action' => 'verify')); ?>" title="<?php _e('Client Verify'); ?>">
            <?php _e('Client Verify');?>
        </a>
    </li>    
</ul>
<h2 class="page-header"><?php _e('Client List'); ?></h2>
<table class="table">
<tr>
	<td><?php _e('logo');?></td>
	<td><?php _e('name');?></td>
	<td><?php _e('brief');?></td>
	<td><?php _e('creater');?></td>
	<td><?php _e('manage');?></td>
</tr>
<?php
	foreach ($list as $client) { ?>
	<tr>
		<td>
			<img src=="<?php echo $client['logo'];?>">
		</td>
		<td>
			<?php echo $client['name'];?>
		</td>
		<td>
			<?php echo $client['description'];?>
		</td>
		<td>
			<!-- <a href="<?php //echo $client['uid'];?>"> -->
				<?php echo $client['username'];?>
			<!-- </a> -->
		</td>
		<td>
			<button id="<?php echo $client['id']?>" onclick="deleteClient(this)">stop</button>
		</td>	
	</tr>
<?php	}
?>
</table>
<script type="text/javascript">
function deleteClient(ob)
{
	console.log(ob.id);
	$.ajax({
		url : "delete",
		data : {id : ob.id},
	});
}
</script>

